# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysDepartment',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('createdatetime', models.DateTimeField(db_column='CreateDateTime', default=django.utils.timezone.now)),
                ('modifydatetime', models.DateTimeField(db_column='ModifyDateTime', default=django.utils.timezone.now)),
                ('creator', models.IntegerField(blank=True, db_column='Creator', null=True)),
                ('modifier', models.IntegerField(blank=True, db_column='Modifier', null=True)),
                ('description', models.CharField(db_column='Description', max_length=100)),
                ('leader', models.CharField(db_column='Leader', max_length=20)),
                ('name', models.CharField(db_column='Name', max_length=20)),
                ('parentid', models.IntegerField(db_column='ParentId')),
            ],
            options={
                'db_table': 'Sys_Department',
            },
        ),
        migrations.CreateModel(
            name='SysLoginlog',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('createdatetime', models.DateTimeField(db_column='CreateDateTime', default=django.utils.timezone.now)),
                ('modifydatetime', models.DateTimeField(db_column='ModifyDateTime', default=django.utils.timezone.now)),
                ('creator', models.IntegerField(blank=True, db_column='Creator', null=True)),
                ('modifier', models.IntegerField(blank=True, db_column='Modifier', null=True)),
                ('clientip', models.CharField(blank=True, db_column='ClientIP', max_length=15, null=True)),
                ('clientmac', models.CharField(blank=True, db_column='ClientMac', max_length=40, null=True)),
                ('username', models.CharField(db_column='UserName', max_length=20)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=40, null=True)),
            ],
            options={
                'db_table': 'Sys_LoginLog',
            },
        ),
        migrations.CreateModel(
            name='SysMenu',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('createdatetime', models.DateTimeField(db_column='CreateDateTime', default=django.utils.timezone.now)),
                ('modifydatetime', models.DateTimeField(db_column='ModifyDateTime', default=django.utils.timezone.now)),
                ('creator', models.IntegerField(blank=True, db_column='Creator', null=True)),
                ('modifier', models.IntegerField(blank=True, db_column='Modifier', null=True)),
                ('name', models.CharField(db_column='Name', max_length=18)),
                ('listorder', models.IntegerField(db_column='ListOrder')),
                ('parentid', models.IntegerField(db_column='ParentId')),
                ('type', models.IntegerField(db_column='Type')),
                ('url', models.CharField(db_column='Url', max_length=300)),
                ('moduleid', models.IntegerField(db_column='ModuleId')),
                ('icon', models.CharField(db_column='Icon', max_length=50)),
            ],
            options={
                'db_table': 'Sys_Menu',
            },
        ),
        migrations.CreateModel(
            name='SysModule',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('createdatetime', models.DateTimeField(db_column='CreateDateTime', default=django.utils.timezone.now)),
                ('modifydatetime', models.DateTimeField(db_column='ModifyDateTime', default=django.utils.timezone.now)),
                ('creator', models.IntegerField(blank=True, db_column='Creator', null=True)),
                ('modifier', models.IntegerField(blank=True, db_column='Modifier', null=True)),
                ('description', models.CharField(db_column='Description', max_length=30)),
                ('name', models.CharField(db_column='Name', max_length=18)),
            ],
            options={
                'db_table': 'Sys_Module',
            },
        ),
        migrations.CreateModel(
            name='SysOperationlog',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('createdatetime', models.DateTimeField(db_column='CreateDateTime', default=django.utils.timezone.now)),
                ('modifydatetime', models.DateTimeField(db_column='ModifyDateTime', default=django.utils.timezone.now)),
                ('creator', models.IntegerField(blank=True, db_column='Creator', null=True)),
                ('modifier', models.IntegerField(blank=True, db_column='Modifier', null=True)),
                ('clientip', models.CharField(db_column='ClientIP', max_length=15)),
                ('clientmac', models.CharField(db_column='ClientMac', max_length=40)),
                ('operationdescription', models.CharField(db_column='OperationDescription', max_length=100)),
                ('operationurl', models.CharField(blank=True, db_column='OperationUrl', max_length=300, null=True)),
                ('username', models.TextField(blank=True, db_column='UserName', null=True)),
            ],
            options={
                'db_table': 'Sys_OperationLog',
            },
        ),
        migrations.CreateModel(
            name='SysRole',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('createdatetime', models.DateTimeField(db_column='CreateDateTime', default=django.utils.timezone.now)),
                ('modifydatetime', models.DateTimeField(db_column='ModifyDateTime', default=django.utils.timezone.now)),
                ('creator', models.IntegerField(blank=True, db_column='Creator', null=True)),
                ('modifier', models.IntegerField(blank=True, db_column='Modifier', null=True)),
                ('concurrencystamp', models.TextField(blank=True, db_column='ConcurrencyStamp', null=True)),
                ('description', models.CharField(db_column='Description', max_length=30)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=256, null=True)),
                ('normalizedname', models.CharField(blank=True, db_column='NormalizedName', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Sys_Role',
            },
        ),
        migrations.CreateModel(
            name='SysRolemenu',
            fields=[
                ('modifydatetime', models.DateTimeField(db_column='ModifyDateTime', default=django.utils.timezone.now)),
                ('creator', models.IntegerField(blank=True, db_column='Creator', null=True)),
                ('modifier', models.IntegerField(blank=True, db_column='Modifier', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('createdatetime', models.DateTimeField(blank=True, db_column='CreateDateTime', null=True)),
                ('menuid', models.IntegerField(db_column='MenuId')),
                ('roleid', models.IntegerField(db_column='RoleId')),
            ],
            options={
                'db_table': 'Sys_RoleMenu',
            },
        ),
        migrations.CreateModel(
            name='SysSystemoption',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('createdatetime', models.DateTimeField(db_column='CreateDateTime', default=django.utils.timezone.now)),
                ('modifydatetime', models.DateTimeField(db_column='ModifyDateTime', default=django.utils.timezone.now)),
                ('creator', models.IntegerField(blank=True, db_column='Creator', null=True)),
                ('modifier', models.IntegerField(blank=True, db_column='Modifier', null=True)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=100, null=True)),
                ('value', models.CharField(db_column='Value', max_length=1000)),
            ],
            options={
                'db_table': 'Sys_SystemOption',
            },
        ),
        migrations.CreateModel(
            name='SysTablecolumn',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('createdatetime', models.DateTimeField(db_column='CreateDateTime', default=django.utils.timezone.now)),
                ('modifydatetime', models.DateTimeField(db_column='ModifyDateTime', default=django.utils.timezone.now)),
                ('creator', models.IntegerField(blank=True, db_column='Creator', null=True)),
                ('modifier', models.IntegerField(blank=True, db_column='Modifier', null=True)),
                ('addvisible', models.IntegerField(db_column='AddVisible')),
                ('datatype', models.IntegerField(db_column='DataType')),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('editorder', models.IntegerField(db_column='EditOrder')),
                ('editvisible', models.IntegerField(db_column='EditVisible')),
                ('enumrange', models.TextField(blank=True, db_column='EnumRange', null=True)),
                ('exportvisible', models.IntegerField(db_column='ExportVisible')),
                ('importvisible', models.IntegerField(db_column='ImportVisible')),
                ('listorder', models.IntegerField(db_column='ListOrder')),
                ('listvisible', models.IntegerField(db_column='ListVisible')),
                ('maxlength', models.IntegerField(db_column='MaxLength')),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('outsql', models.TextField(blank=True, db_column='OutSql', null=True)),
                ('primarkey', models.IntegerField(db_column='PrimarKey')),
                ('required', models.IntegerField(db_column='Required')),
                ('searchvisible', models.IntegerField(db_column='SearchVisible')),
                ('tableid', models.IntegerField(db_column='TableId')),
                ('vieworder', models.IntegerField(db_column='ViewOrder')),
                ('viewvisible', models.IntegerField(db_column='ViewVisible')),
            ],
            options={
                'db_table': 'Sys_TableColumn',
            },
        ),
        migrations.CreateModel(
            name='SysTablelist',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('createdatetime', models.DateTimeField(db_column='CreateDateTime', default=django.utils.timezone.now)),
                ('modifydatetime', models.DateTimeField(db_column='ModifyDateTime', default=django.utils.timezone.now)),
                ('creator', models.IntegerField(blank=True, db_column='Creator', null=True)),
                ('modifier', models.IntegerField(blank=True, db_column='Modifier', null=True)),
                ('defaultfilter', models.TextField(blank=True, db_column='DefaultFilter', null=True)),
                ('defaultsort', models.TextField(blank=True, db_column='DefaultSort', null=True)),
                ('deletetablename', models.TextField(blank=True, db_column='DeleteTableName', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('extendfunction', models.TextField(blank=True, db_column='ExtendFunction', null=True)),
                ('forbiddenaddfilter', models.TextField(blank=True, db_column='ForbiddenAddFilter', null=True)),
                ('forbiddendeletefilter', models.TextField(blank=True, db_column='ForbiddenDeleteFilter', null=True)),
                ('forbiddenupdatefilter', models.TextField(blank=True, db_column='ForbiddenUpdateFilter', null=True)),
                ('importtype', models.IntegerField(db_column='ImportType')),
                ('isview', models.IntegerField(db_column='IsView')),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('allowdelete', models.IntegerField(db_column='AllowDelete')),
                ('allowedit', models.IntegerField(db_column='AllowEdit')),
                ('allowexport', models.IntegerField(db_column='AllowExport')),
                ('allowimport', models.IntegerField(db_column='AllowImport')),
                ('allowview', models.IntegerField(db_column='AllowView')),
                ('allowadd', models.IntegerField(db_column='AllowAdd')),
            ],
            options={
                'db_table': 'Sys_TableList',
            },
        ),
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('createdatetime', models.DateTimeField(db_column='CreateDateTime', default=django.utils.timezone.now)),
                ('modifydatetime', models.DateTimeField(db_column='ModifyDateTime', default=django.utils.timezone.now)),
                ('creator', models.IntegerField(blank=True, db_column='Creator', null=True)),
                ('modifier', models.IntegerField(blank=True, db_column='Modifier', null=True)),
                ('accessfailedcount', models.IntegerField(db_column='AccessFailedCount')),
                ('email', models.CharField(blank=True, db_column='Email', max_length=256, null=True)),
                ('emailconfirmed', models.IntegerField(db_column='EmailConfirmed')),
                ('lockoutenabled', models.IntegerField(db_column='LockoutEnabled')),
                ('lockoutend', models.TextField(blank=True, db_column='LockoutEnd', null=True)),
                ('normalizedemail', models.CharField(blank=True, db_column='NormalizedEmail', max_length=100, null=True)),
                ('normalizedusername', models.CharField(blank=True, db_column='NormalizedUserName', max_length=100, null=True)),
                ('passwordhash', models.TextField(blank=True, db_column='PasswordHash', null=True)),
                ('phonenumber', models.TextField(blank=True, db_column='PhoneNumber', null=True)),
                ('phonenumberconfirmed', models.IntegerField(db_column='PhoneNumberConfirmed')),
                ('realname', models.TextField(blank=True, db_column='RealName', null=True)),
                ('securitystamp', models.TextField(blank=True, db_column='SecurityStamp', null=True)),
                ('status', models.IntegerField(db_column='Status')),
                ('twofactorenabled', models.IntegerField(db_column='TwoFactorEnabled')),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=256, null=True)),
            ],
            options={
                'db_table': 'Sys_User',
            },
        ),
        migrations.CreateModel(
            name='SysUserdepartment',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('createdatetime', models.DateTimeField(db_column='CreateDateTime', default=django.utils.timezone.now)),
                ('modifydatetime', models.DateTimeField(db_column='ModifyDateTime', default=django.utils.timezone.now)),
                ('creator', models.IntegerField(blank=True, db_column='Creator', null=True)),
                ('modifier', models.IntegerField(blank=True, db_column='Modifier', null=True)),
                ('departmentid', models.IntegerField(db_column='DepartmentId')),
                ('userid', models.IntegerField(db_column='UserId')),
            ],
            options={
                'db_table': 'Sys_UserDepartment',
            },
        ),
        migrations.CreateModel(
            name='SysUserrole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(db_column='UserId')),
                ('roleid', models.IntegerField(db_column='RoleId')),
            ],
            options={
                'db_table': 'Sys_UserRole',
            },
        ),
        migrations.CreateModel(
            name='TestLeader',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('createdatetime', models.DateTimeField(db_column='CreateDateTime', default=django.utils.timezone.now)),
                ('modifydatetime', models.DateTimeField(db_column='ModifyDateTime', default=django.utils.timezone.now)),
                ('creator', models.IntegerField(blank=True, db_column='Creator', null=True)),
                ('modifier', models.IntegerField(blank=True, db_column='Modifier', null=True)),
                ('name', models.CharField(db_column='Name', max_length=30)),
                ('parentid', models.IntegerField(db_column='ParentId')),
                ('type', models.CharField(db_column='Type', max_length=30)),
            ],
            options={
                'db_table': 'Test_Leader',
            },
        ),
    ]
