# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kingWeb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysrole',
            name='concurrencystamp',
        ),
        migrations.RemoveField(
            model_name='sysrole',
            name='normalizedname',
        ),
    ]
