# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 01:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kingWeb', '0002_auto_20180621_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysUserProfile',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('createdatetime', models.DateTimeField(db_column='CreateDateTime', default=django.utils.timezone.now)),
                ('modifydatetime', models.DateTimeField(db_column='ModifyDateTime', default=django.utils.timezone.now)),
                ('creator', models.IntegerField(blank=True, db_column='Creator', null=True)),
                ('modifier', models.IntegerField(blank=True, db_column='Modifier', null=True)),
                ('status', models.SmallIntegerField(db_column='Status')),
                ('imagepath', models.CharField(blank=True, db_column='ImagePath', max_length=256, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Sys_UserProfile',
            },
        ),
    ]
