# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingWeb', '0003_sysuserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systablecolumn',
            name='addvisible',
            field=models.IntegerField(db_column='AddVisible', default=0),
        ),
        migrations.AlterField(
            model_name='systablecolumn',
            name='datatype',
            field=models.TextField(blank=True, db_column='DataType', null=True),
        ),
        migrations.AlterField(
            model_name='systablecolumn',
            name='editorder',
            field=models.IntegerField(db_column='EditOrder', default=0),
        ),
        migrations.AlterField(
            model_name='systablecolumn',
            name='editvisible',
            field=models.IntegerField(db_column='EditVisible', default=0),
        ),
        migrations.AlterField(
            model_name='systablecolumn',
            name='exportvisible',
            field=models.IntegerField(db_column='ExportVisible', default=0),
        ),
        migrations.AlterField(
            model_name='systablecolumn',
            name='importvisible',
            field=models.IntegerField(db_column='ImportVisible', default=0),
        ),
        migrations.AlterField(
            model_name='systablecolumn',
            name='listorder',
            field=models.IntegerField(db_column='ListOrder', default=0),
        ),
        migrations.AlterField(
            model_name='systablecolumn',
            name='listvisible',
            field=models.IntegerField(db_column='ListVisible', default=0),
        ),
        migrations.AlterField(
            model_name='systablecolumn',
            name='maxlength',
            field=models.IntegerField(db_column='MaxLength', default=0),
        ),
        migrations.AlterField(
            model_name='systablecolumn',
            name='primarkey',
            field=models.IntegerField(db_column='PrimarKey', default=0),
        ),
        migrations.AlterField(
            model_name='systablecolumn',
            name='required',
            field=models.IntegerField(db_column='Required', default=0),
        ),
        migrations.AlterField(
            model_name='systablecolumn',
            name='searchvisible',
            field=models.IntegerField(db_column='SearchVisible', default=0),
        ),
        migrations.AlterField(
            model_name='systablecolumn',
            name='vieworder',
            field=models.IntegerField(db_column='ViewOrder', default=0),
        ),
        migrations.AlterField(
            model_name='systablecolumn',
            name='viewvisible',
            field=models.IntegerField(db_column='ViewVisible', default=0),
        ),
        migrations.AlterField(
            model_name='sysuserprofile',
            name='status',
            field=models.SmallIntegerField(db_column='Status', default=0),
        ),
    ]
