# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kingWeb', '0003_department'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
