# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingWeb', '0004_auto_20180629_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysloginlog',
            name='clientmac',
        ),
        migrations.RemoveField(
            model_name='sysoperationlog',
            name='clientmac',
        ),
        migrations.AlterField(
            model_name='systablelist',
            name='allowadd',
            field=models.IntegerField(db_column='AllowAdd', default=0),
        ),
        migrations.AlterField(
            model_name='systablelist',
            name='allowdelete',
            field=models.IntegerField(db_column='AllowDelete', default=0),
        ),
        migrations.AlterField(
            model_name='systablelist',
            name='allowedit',
            field=models.IntegerField(db_column='AllowEdit', default=0),
        ),
        migrations.AlterField(
            model_name='systablelist',
            name='allowexport',
            field=models.IntegerField(db_column='AllowExport', default=0),
        ),
        migrations.AlterField(
            model_name='systablelist',
            name='allowimport',
            field=models.IntegerField(db_column='AllowImport', default=0),
        ),
        migrations.AlterField(
            model_name='systablelist',
            name='allowview',
            field=models.IntegerField(db_column='AllowView', default=0),
        ),
        migrations.AlterField(
            model_name='systablelist',
            name='importtype',
            field=models.IntegerField(blank=True, db_column='ImportType'),
        ),
        migrations.AlterField(
            model_name='systablelist',
            name='isview',
            field=models.IntegerField(db_column='IsView', default=0),
        ),
    ]
