# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kingWeb', '0005_auto_20180716_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SysUser',
        ),
    ]
