# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingWeb', '0006_delete_sysuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysloginlog',
            name='clientinfo',
            field=models.CharField(blank=True, db_column='ClientInfo', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='sysoperationlog',
            name='clientinfo',
            field=models.CharField(blank=True, db_column='ClientInfo', max_length=40, null=True),
        ),
    ]
