# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-28 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kingWeb', '0008_auto_20180716_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systablelist',
            name='allowadd',
        ),
    ]
