# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-30 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingWeb', '0009_remove_systablelist_allowadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='systablelist',
            name='allowadd',
            field=models.IntegerField(db_column='AllowAdd', default=0),
        ),
        migrations.AlterField(
            model_name='sysdepartment',
            name='parentid',
            field=models.IntegerField(blank=True, db_column='ParentId', null=True),
        ),
        migrations.AlterField(
            model_name='sysmenu',
            name='parentid',
            field=models.IntegerField(blank=True, db_column='ParentId', null=True),
        ),
    ]
