# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-21 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingWeb', '0016_auto_20180921_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systablecolumn',
            name='tableid',
            field=models.IntegerField(db_column='TableId'),
        ),
    ]
