# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-01 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingWeb', '0017_auto_20180921_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='systablelist',
            name='allowdetail',
            field=models.IntegerField(db_column='AllowDetail', default=0),
        ),
    ]
