# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-07 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingWeb', '0020_auto_20181004_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='systablecolumn',
            name='selectrange',
            field=models.TextField(blank=True, db_column='SelectRange', null=True),
        ),
    ]
