# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-07 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingWeb', '0021_systablecolumn_selectrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='testleader',
            name='test1',
            field=models.CharField(db_column='radio', default='', max_length=300),
        ),
        migrations.AddField(
            model_name='testleader',
            name='test2',
            field=models.CharField(db_column='checkbox', default='', max_length=300),
        ),
        migrations.AddField(
            model_name='testleader',
            name='test3',
            field=models.CharField(db_column='date', default='', max_length=300),
        ),
    ]
