# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-07 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingWeb', '0022_auto_20190107_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testleader',
            name='test1',
            field=models.CharField(db_column='Test1', default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='testleader',
            name='test2',
            field=models.CharField(db_column='Test2', default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='testleader',
            name='test3',
            field=models.CharField(db_column='Test3', default='', max_length=300),
        ),
    ]
