# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-08 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingWeb', '0023_auto_20190107_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='systablelist',
            name='columnperrow',
            field=models.IntegerField(db_column='ColumnPerRow', default=0),
        ),
        migrations.AddField(
            model_name='systablelist',
            name='vieweditwidthheight',
            field=models.TextField(blank=True, db_column='ViewEditWidthHeight', null=True),
        ),
    ]
