# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-13 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingWeb', '0025_systablecolumn_forbiddenfileextension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testleader',
            name='test1',
            field=models.CharField(db_column='Test1', default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='testleader',
            name='test2',
            field=models.CharField(db_column='Test2', default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='testleader',
            name='test3',
            field=models.CharField(db_column='Test3', default='', max_length=300, null=True),
        ),
    ]
