# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-16 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingWeb', '0027_systablelist_javascript'),
    ]

    operations = [
        migrations.AddField(
            model_name='systablecolumn',
            name='validationrule',
            field=models.TextField(blank=True, db_column='ValidationRule', default=''),
        ),
        migrations.AlterField(
            model_name='systablecolumn',
            name='datatype',
            field=models.TextField(blank=True, db_column='DataType', default=''),
        ),
        migrations.AlterField(
            model_name='systablecolumn',
            name='description',
            field=models.TextField(blank=True, db_column='Description', default=''),
        ),
        migrations.AlterField(
            model_name='systablecolumn',
            name='enumrange',
            field=models.TextField(blank=True, db_column='EnumRange', default=''),
        ),
        migrations.AlterField(
            model_name='systablecolumn',
            name='forbiddenfileextension',
            field=models.TextField(blank=True, db_column='ForbiddenFileExtension', default=''),
        ),
        migrations.AlterField(
            model_name='systablecolumn',
            name='name',
            field=models.TextField(blank=True, db_column='Name', default=''),
        ),
        migrations.AlterField(
            model_name='systablecolumn',
            name='outsql',
            field=models.TextField(blank=True, db_column='OutSql', default=''),
        ),
        migrations.AlterField(
            model_name='systablecolumn',
            name='selectrange',
            field=models.TextField(blank=True, db_column='SelectRange', default=''),
        ),
        migrations.AlterField(
            model_name='systablelist',
            name='defaultfilter',
            field=models.TextField(blank=True, db_column='DefaultFilter', default=''),
        ),
        migrations.AlterField(
            model_name='systablelist',
            name='defaultsort',
            field=models.TextField(blank=True, db_column='DefaultSort', default=''),
        ),
        migrations.AlterField(
            model_name='systablelist',
            name='deletetablename',
            field=models.TextField(blank=True, db_column='DeleteTableName', default=''),
        ),
        migrations.AlterField(
            model_name='systablelist',
            name='description',
            field=models.TextField(blank=True, db_column='Description', default=''),
        ),
        migrations.AlterField(
            model_name='systablelist',
            name='extendfunction',
            field=models.TextField(blank=True, db_column='ExtendFunction', default=''),
        ),
        migrations.AlterField(
            model_name='systablelist',
            name='forbiddenaddfilter',
            field=models.TextField(blank=True, db_column='ForbiddenAddFilter', default=''),
        ),
        migrations.AlterField(
            model_name='systablelist',
            name='forbiddendeletefilter',
            field=models.TextField(blank=True, db_column='ForbiddenDeleteFilter', default=''),
        ),
        migrations.AlterField(
            model_name='systablelist',
            name='forbiddenupdatefilter',
            field=models.TextField(blank=True, db_column='ForbiddenUpdateFilter', default=''),
        ),
        migrations.AlterField(
            model_name='systablelist',
            name='javascript',
            field=models.TextField(blank=True, db_column='JavaScript', default=''),
        ),
        migrations.AlterField(
            model_name='systablelist',
            name='name',
            field=models.TextField(blank=True, db_column='Name', default=''),
        ),
        migrations.AlterField(
            model_name='systablelist',
            name='topextendfunction',
            field=models.TextField(blank=True, db_column='TopExtendFunction', default=''),
        ),
        migrations.AlterField(
            model_name='systablelist',
            name='vieweditwidthheight',
            field=models.TextField(blank=True, db_column='ViewEditWidthHeight', default=''),
        ),
    ]
