# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-17 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingWeb', '0028_auto_20190116_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='systablecolumn',
            name='customcontent',
            field=models.TextField(blank=True, db_column='CustomContent', default=''),
        ),
    ]
