# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-17 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kingWeb', '0030_auto_20190117_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systablecolumn',
            old_name='primarkey',
            new_name='primarykey',
        ),
    ]
