# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-17 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingWeb', '0031_auto_20190117_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systablecolumn',
            name='primarykey',
            field=models.IntegerField(db_column='PrimaryKey', default=0),
        ),
    ]
