# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-22 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingWeb', '0032_auto_20190117_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysdepartment',
            name='parentid',
            field=models.IntegerField(blank=True, db_column='ParentId', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sysloginlog',
            name='username',
            field=models.CharField(db_column='UserName', default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sysmenu',
            name='parentid',
            field=models.IntegerField(blank=True, db_column='ParentId', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='systablecolumn',
            name='name',
            field=models.TextField(db_column='Name'),
        ),
        migrations.AlterField(
            model_name='systablelist',
            name='name',
            field=models.TextField(db_column='Name'),
        ),
    ]
